# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 09:11
from __future__ import unicode_literals

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
        ('results', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('status', models.CharField(choices=[('h', 'Скрыт'), ('p', 'Опубликован')], default='h', max_length=1, verbose_name='Статус публикации')),
                ('title', models.CharField(default='Название курса', max_length=256, verbose_name='Название курса')),
                ('description', models.TextField(blank=True, default='Здесь должно быть описание курса', max_length=16384, verbose_name='Короткое описание')),
                ('slug', models.CharField(help_text='должен быть уникальным в рамках вуза', max_length=32, verbose_name='Код курса')),
                ('authors_ordering', models.CharField(blank=True, help_text='id авторов через пробел', max_length=500, verbose_name='Порядок авторов')),
                ('about', models.TextField(blank=True, verbose_name='О курсе')),
                ('cover', models.ImageField(blank=True, upload_to=courses.models.Course.get_cover_path, verbose_name='Обложка')),
                ('video', models.URLField(blank=True, default='', help_text='URL видео', max_length=500, verbose_name='Промовидео')),
                ('video_cover', models.ImageField(blank=True, upload_to=courses.models.Course.get_video_cover_path, verbose_name='Картинка для видео')),
                ('workload', models.PositiveIntegerField(blank=True, null=True, verbose_name='часов в неделю')),
                ('points', models.PositiveIntegerField(blank=True, null=True, verbose_name='зачётных единиц')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность (недель)')),
                ('results_text', models.TextField(blank=True, default='', max_length=16384, verbose_name='Результаты обучения')),
                ('external_link', models.URLField(blank=True, null=True, verbose_name='Внешняя ссылка')),
                ('type', models.CharField(choices=[('0', 'Онлайн-курс'), ('1', 'Смешанная'), ('2', 'Традиционная')], default='0', max_length=1, verbose_name='Технология')),
                ('authors', models.ManyToManyField(blank=True, related_name='course_authors', to='persons.Person', verbose_name='Авторы')),
                ('results', models.ManyToManyField(blank=True, to='results.Result', verbose_name='Результаты обучения')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('status', models.CharField(choices=[('h', 'Скрыт'), ('p', 'Опубликован')], default='h', max_length=1, verbose_name='Статус публикации')),
                ('slug', models.SlugField(help_text='Например, winter_2016, fall_2015', verbose_name='Код сессии')),
                ('startdate', models.DateTimeField(verbose_name='Начало сессии курса')),
                ('enddate', models.DateTimeField(verbose_name='Конец сессии курса')),
            ],
            options={
                'verbose_name': 'сессия',
                'verbose_name_plural': 'сессии',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='sessions',
            field=models.ManyToManyField(blank=True, to='courses.Session', verbose_name='Сессии'),
        ),
        migrations.AddField(
            model_name='course',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='course_staff', to='persons.Person', verbose_name='Команда курса'),
        ),
    ]
