# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='slug',
            field=models.SlugField(default='www', help_text='winter_2016, fall_2015', verbose_name='Код сессии'),
            preserve_default=False,
        ),
    ]
