# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='external_link',
            field=models.URLField(blank=True, null=True, verbose_name='Внешняя ссылка'),
        ),
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('0', 'Онлайн-курс'), ('1', 'Смешанная'), ('2', 'Традиционная')], default='0', max_length=1, verbose_name='Технология'),
        ),
    ]
