# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 11:21
from __future__ import unicode_literals

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover',
            field=models.ImageField(blank=True, upload_to=courses.models.Course.get_cover_path, verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, default='Здесь должно быть описание курса', max_length=16384, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='results',
            field=models.ManyToManyField(blank=True, to='results.Result', verbose_name='Результаты обучения'),
        ),
        migrations.AlterField(
            model_name='course',
            name='video_cover',
            field=models.ImageField(blank=True, upload_to=courses.models.Course.get_video_cover_path, verbose_name='Картинка для видео'),
        ),
    ]
