# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
        ('courses', '0002_session_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'курс', 'verbose_name_plural': 'курсы'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'сессия', 'verbose_name_plural': 'сессии'},
        ),
        migrations.AddField(
            model_name='course',
            name='staff',
            field=models.ManyToManyField(to='persons.Person'),
        ),
        migrations.AlterField(
            model_name='session',
            name='enddate',
            field=models.DateTimeField(verbose_name='Конец сессии курса'),
        ),
        migrations.AlterField(
            model_name='session',
            name='slug',
            field=models.SlugField(help_text='Например, winter_2016, fall_2015', verbose_name='Код сессии'),
        ),
        migrations.AlterField(
            model_name='session',
            name='startdate',
            field=models.DateTimeField(verbose_name='Начало сессии курса'),
        ),
    ]
