# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20161219_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='course_authors', to='persons.Person', verbose_name='Авторы'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.CharField(help_text='должен быть уникальным в рамках вуза', max_length=32, verbose_name='Код курса'),
        ),
    ]
