# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_session_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='enddate',
            field=models.DateTimeField(verbose_name='Конец сессии курса'),
        ),
        migrations.AlterField(
            model_name='session',
            name='slug',
            field=models.SlugField(help_text='Например, winter_2016, fall_2015', verbose_name='Код сессии'),
        ),
        migrations.AlterField(
            model_name='session',
            name='startdate',
            field=models.DateTimeField(verbose_name='Начало сессии курса'),
        ),
    ]
