# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20161207_1511'),
        ('courses', '0003_auto_20161206_2051'),
    ]

    operations = [
    ]
