# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-12 20:32
from __future__ import unicode_literals

import cms.models
from django.db import migrations, models
import django.db.models.deletion
import jsoneditor.fields.django_jsonfield
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('status', models.CharField(choices=[('h', 'Скрыт'), ('p', 'Опубликован')], default='h', max_length=1, verbose_name='Статус публикации')),
                ('title', models.CharField(default=cms.models.random_component_key, max_length=256, verbose_name='Название компонента')),
                ('slug', models.SlugField(verbose_name='Код')),
                ('dev_description', tinymce.models.HTMLField()),
                ('weight', models.IntegerField(verbose_name='Вес')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Контент')),
                ('json', jsoneditor.fields.django_jsonfield.JSONField()),
                ('components', models.ManyToManyField(blank=True, related_name='_component_components_+', to='cms.Component', verbose_name='Вложенные компоненты')),
            ],
            options={
                'verbose_name_plural': 'компонент',
                'verbose_name': 'компонент',
            },
        ),
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=cms.models.random_component_key, max_length=256, verbose_name='Название типа компонента')),
                ('dev_description', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('status', models.CharField(choices=[('h', 'Скрыт'), ('p', 'Опубликован')], default='h', max_length=1, verbose_name='Статус публикации')),
                ('title', models.CharField(default=cms.models.random_container_key, max_length=256, verbose_name='Название контейнера')),
                ('slug', models.SlugField(verbose_name='Код')),
                ('dev_description', tinymce.models.HTMLField()),
                ('weight', models.IntegerField(verbose_name='Вес')),
                ('containers', models.ManyToManyField(blank=True, related_name='_container_containers_+', to='cms.Container', verbose_name='Вложенные контейнеры')),
            ],
            options={
                'verbose_name_plural': 'контейнеры',
                'verbose_name': 'контейнер',
            },
        ),
        migrations.CreateModel(
            name='ContainerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=cms.models.random_container_key, max_length=256, verbose_name='Название типа контейнера')),
                ('dev_description', tinymce.models.HTMLField()),
            ],
        ),
        migrations.AddField(
            model_name='container',
            name='type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cms.ContainerType'),
        ),
        migrations.AddField(
            model_name='component',
            name='type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cms.ComponentType'),
        ),
    ]
