# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 09:11
from __future__ import unicode_literals

import cms.models
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('status', models.CharField(choices=[('h', 'Скрыт'), ('p', 'Опубликован')], default='h', max_length=1, verbose_name='Статус публикации')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default=cms.models.random_component_key, max_length=256, verbose_name='Название компонента')),
                ('slug', models.SlugField(unique=True, verbose_name='Код')),
                ('dev_description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='DEV_DESCRIPTION')),
                ('weight', models.IntegerField(default=0, verbose_name='Вес')),
                ('content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Контент')),
                ('json', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='JSON')),
            ],
            options={
                'verbose_name': 'компонент',
                'verbose_name_plural': 'компонент',
            },
        ),
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default=cms.models.random_component_key, max_length=256, verbose_name='Название типа компонента')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Код')),
                ('dev_description', tinymce.models.HTMLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'тип компонента',
                'verbose_name_plural': 'типы компонентов',
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('status', models.CharField(choices=[('h', 'Скрыт'), ('p', 'Опубликован')], default='h', max_length=1, verbose_name='Статус публикации')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default=cms.models.random_container_key, max_length=256, verbose_name='Название контейнера')),
                ('slug', models.SlugField(unique=True, verbose_name='Код')),
                ('dev_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('weight', models.IntegerField(default=0, verbose_name='Вес')),
                ('components', models.ManyToManyField(blank=True, to='cms.Component', verbose_name='Вложенные компоненты')),
                ('containers', models.ManyToManyField(blank=True, related_name='_container_containers_+', to='cms.Container', verbose_name='Вложенные контейнеры')),
            ],
            options={
                'verbose_name': 'контейнер',
                'verbose_name_plural': 'контейнеры',
            },
        ),
        migrations.CreateModel(
            name='ContainerType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default=cms.models.random_container_key, max_length=256, verbose_name='Название типа контейнера')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Код')),
                ('dev_description', tinymce.models.HTMLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'тип контейнера',
                'verbose_name_plural': 'типы контейнера',
            },
        ),
        migrations.AddField(
            model_name='container',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.ContainerType'),
        ),
        migrations.AddField(
            model_name='component',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.ComponentType'),
        ),
    ]
