# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-12 23:06
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20170413_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='component',
            name='dev_description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
