# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-12 23:23
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20170413_0406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componenttype',
            options={'verbose_name': 'тип компонента', 'verbose_name_plural': 'типы компонентов'},
        ),
        migrations.AlterModelOptions(
            name='containertype',
            options={'verbose_name': 'тип контейнера', 'verbose_name_plural': 'типы контейнера'},
        ),
        migrations.AlterField(
            model_name='componenttype',
            name='dev_description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='dev_description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
