# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-13 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20170413_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='components',
        ),
        migrations.AddField(
            model_name='componenttype',
            name='slug',
            field=models.SlugField(null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='container',
            name='components',
            field=models.ManyToManyField(blank=True, to='cms.Component', verbose_name='Вложенные компоненты'),
        ),
        migrations.AddField(
            model_name='containertype',
            name='slug',
            field=models.SlugField(null=True, verbose_name='Код'),
        ),
    ]
