# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20170413_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='dev_description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='DEV_DESCRIPTION'),
        ),
        migrations.AlterField(
            model_name='component',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='component',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='componenttype',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='componenttype',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='container',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='container',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='Код'),
        ),
    ]
