# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.10.3 on 2016-12-07 14:30
=======
# Generated by Django 1.10.3 on 2016-12-07 14:58
>>>>>>> a665de25527fd283f08450f261dfd7638874b23f
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('status', models.CharField(choices=[('h', 'Скрыт'), ('p', 'Опубликован')], default='h', max_length=1, verbose_name='Статус публикации')),
                ('title', models.CharField(default='', max_length=512, verbose_name='Компетенция')),
            ],
            options={
<<<<<<< HEAD
                'verbose_name_plural': 'компетенции',
                'verbose_name': 'компетенция',
=======
                'verbose_name': 'компетенция',
                'verbose_name_plural': 'компетенции',
>>>>>>> a665de25527fd283f08450f261dfd7638874b23f
            },
        ),
    ]
