# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0002_remove_profession_competences'),
        ('competences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='professions.Profession'),
        ),
    ]
