# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicemodulespool',
            name='modules',
            field=models.ManyToManyField(to='modules.Module', verbose_name='модули'),
        ),
        migrations.AlterField(
            model_name='educationalprogramtrajectoriespool',
            name='modules',
            field=models.ManyToManyField(to='modules.Module', verbose_name='модули'),
        ),
        migrations.AlterField(
            model_name='generalbasemodulespool',
            name='modules',
            field=models.ManyToManyField(to='modules.Module', verbose_name='модули'),
        ),
    ]
