# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choicepool',
            options={'verbose_name': 'пул модулей по выбору', 'verbose_name_plural': 'пулы модулей по выбору'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'модуль', 'verbose_name_plural': 'модули'},
        ),
        migrations.AlterModelOptions(
            name='modulespool',
            options={'verbose_name': 'пул модулей', 'verbose_name_plural': 'пулы модулей'},
        ),
    ]
