# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0001_initial'),
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='disciplines',
            field=models.ManyToManyField(to='discipline.Discipline'),
        ),
    ]
