# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_remove_module_disciplines'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='semester',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Семестр'),
        ),
    ]
