# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
        ('modules', '0002_auto_20161203_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalProgramTrajectoriesPool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Название пула', max_length=256, verbose_name='Название пула модулей траектории обр. программ')),
                ('description', models.TextField(blank=True, default='', max_length=16384, verbose_name='Описание')),
                ('modules', models.ManyToManyField(to='modules.Module')),
            ],
            options={
                'verbose_name': 'пул модулей траектории обр. программ',
                'verbose_name_plural': 'пулы модулей траектории обр. программ',
            },
        ),
        migrations.CreateModel(
            name='GeneralBaseModulesPool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Название пула', max_length=256, verbose_name='Название базового модуля программы')),
                ('description', models.TextField(blank=True, default='', max_length=16384, verbose_name='Описание')),
                ('modules', models.ManyToManyField(to='modules.Module')),
            ],
            options={
                'verbose_name': 'базовый модуль программы',
                'verbose_name_plural': 'базовые модули программы',
            },
        ),
        migrations.RenameModel(
            old_name='ChoicePool',
            new_name='ChoiceModulesPool',
        ),
        migrations.RemoveField(
            model_name='modulespool',
            name='modules',
        ),
        migrations.DeleteModel(
            name='ModulesPool',
        ),
    ]
