# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_auto_20161205_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='disciplines1',
            new_name='disciplines',
        ),
    ]
