# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_remove_module_dependencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Название модуля'),
        ),
    ]
