# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_module_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choicemodulespool',
            name='modules',
        ),
        migrations.RemoveField(
            model_name='educationalprogramtrajectoriespool',
            name='modules',
        ),
        migrations.RemoveField(
            model_name='generalbasemodulespool',
            name='modules',
        ),
    ]
