# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_remove_module_dependencies'),
        ('modules', '0002_auto_20161213_1206'),
    ]

    operations = [
    ]
