# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_auto_20170220_1112'),
        ('modules', '0004_auto_20170220_1112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChoiceModulesPool',
        ),
        migrations.DeleteModel(
            name='EducationalProgramTrajectoriesPool',
        ),
        migrations.DeleteModel(
            name='GeneralBaseModulesPool',
        ),
    ]
