# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_auto_20161215_1853'),
        ('modules', '0002_auto_20161213_1206'),
    ]

    operations = [
    ]
