# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Имя', max_length=32, verbose_name='Имя пользователя')),
                ('last_name', models.CharField(default='Фамилия', max_length=32, verbose_name='Фамилия пользователя')),
                ('second_name', models.CharField(blank=True, default='Отчество', max_length=32, verbose_name='Отчество пользователя')),
                ('sex', models.CharField(choices=[('U', 'Не выбран'), ('F', 'Женский'), ('M', 'Мужской')], default='U', max_length=1)),
                ('alt_email', models.EmailField(blank=True, max_length=254, verbose_name='Альтернативный e-mail')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('birthday_date', models.DateField(blank=True, verbose_name='Дата рождения')),
                ('biography', models.TextField(blank=True, default='Биография', verbose_name='Биография пользователя')),
            ],
        ),
    ]
