# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='biography',
            field=models.TextField(blank=True, default='', verbose_name='Биография пользователя'),
        ),
        migrations.AlterField(
            model_name='person',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='Russia', max_length=2),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(default='', max_length=32, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='', max_length=32, verbose_name='Фамилия пользователя'),
        ),
        migrations.AlterField(
            model_name='person',
            name='second_name',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Отчество пользователя'),
        ),
    ]
