# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_auto_20161202_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthday_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
