# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Название майнора', max_length=256, verbose_name='Название майнора')),
                ('description', models.TextField(blank=True, default='', max_length=16384, verbose_name='Описание майнора')),
                ('status', models.CharField(choices=[('h', 'Скрыт'), ('p', 'Опубликован')], default='h', max_length=1, verbose_name='Статус публикации')),
                ('courses', models.ManyToManyField(to='courses.Course', verbose_name='Варианты реализации майнора')),
            ],
            options={
                'verbose_name': 'майнор',
                'verbose_name_plural': 'майноры',
            },
        ),
        migrations.CreateModel(
            name='MinorsPool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Название пула', max_length=256, verbose_name='Название пула майноров')),
                ('description', models.TextField(blank=True, default='', max_length=16384, verbose_name='Описание')),
                ('modules', models.ManyToManyField(to='minors.Minor')),
            ],
            options={
                'verbose_name': 'пул майноров',
                'verbose_name_plural': 'пулы майноров',
            },
        ),
    ]
