# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', verbose_name='Название дисциплины')),
                ('name1', models.TextField(default='', verbose_name='Название дисциплины')),
            ],
        ),
    ]
