# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('discipline', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'verbose_name': 'дисциплина', 'verbose_name_plural': 'дисциплины'},
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='name1',
        ),
        migrations.AddField(
            model_name='discipline',
            name='courses',
            field=models.ManyToManyField(to='courses.Course', verbose_name='Варианты реализации дисциплины'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(default='', max_length=256, verbose_name='Название дисциплины'),
        ),
    ]
