# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competences', '__first__'),
        ('persons', '0001_initial'),
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceGroup',
            fields=[
                ('archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('status', models.CharField(choices=[('h', 'Скрыт'), ('p', 'Опубликован')], default='h', max_length=1, verbose_name='Статус публикации')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=2048, verbose_name='Наименование группы выбора')),
                ('labor', models.IntegerField(default=3, verbose_name='Трудоёмкость группы')),
                ('number', models.IntegerField(verbose_name='Номер группы выбора')),
            ],
            options={
                'verbose_name': 'группа выбора',
                'verbose_name_plural': 'группы выбора',
            },
        ),
        migrations.CreateModel(
            name='ChoiceGroupType',
            fields=[
                ('archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('status', models.CharField(choices=[('h', 'Скрыт'), ('p', 'Опубликован')], default='h', max_length=1, verbose_name='Статус публикации')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=2048, verbose_name='Наименование типы группы выбора')),
            ],
            options={
                'verbose_name': 'тип группы выбора',
                'verbose_name_plural': 'типы группы выбора',
            },
        ),
        migrations.CreateModel(
            name='LearningPlan',
            fields=[
                ('archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('status', models.CharField(choices=[('h', 'Скрыт'), ('p', 'Опубликован')], default='h', max_length=1, verbose_name='Статус публикации')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uni_displayableTitle', models.CharField(blank=True, max_length=32, null=True, verbose_name='Версия')),
                ('uni_number', models.CharField(blank=True, max_length=32, null=True, verbose_name='Номер УП')),
                ('uni_active', models.CharField(blank=True, max_length=32, null=True, verbose_name='Текущая версия')),
                ('uni_title', models.CharField(blank=True, max_length=32, null=True, verbose_name='Название')),
                ('uni_stage', models.BooleanField(default=True, verbose_name='План утверждён')),
                ('uni_loadTimeType', models.CharField(blank=True, max_length=32, null=True, verbose_name='Единица измерения нагрузки')),
                ('uni_html', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'учебный план',
                'verbose_name_plural': 'учебные планы',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('status', models.CharField(choices=[('h', 'Скрыт'), ('p', 'Опубликован')], default='h', max_length=1, verbose_name='Статус публикации')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('b', 'бакалавриат'), ('m', 'магистратура'), ('s', 'специалитет')], default='b', max_length=1, verbose_name='Уровень программы')),
                ('title', models.CharField(default='', max_length=256, verbose_name='Наименование образовательной программы')),
                ('training_direction', models.CharField(default='', max_length=256, verbose_name='Направление подготовки')),
                ('chief', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.Person', verbose_name='Руководитель образовательной программы')),
                ('competences', models.ManyToManyField(blank=True, to='competences.Competence')),
                ('learning_plans', models.ManyToManyField(blank=True, to='programs.LearningPlan')),
            ],
            options={
                'verbose_name': 'программа',
                'verbose_name_plural': 'программы',
            },
        ),
        migrations.CreateModel(
            name='ProgramCompetence',
            fields=[
                ('archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('status', models.CharField(choices=[('h', 'Скрыт'), ('p', 'Опубликован')], default='h', max_length=1, verbose_name='Статус публикации')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=2048, verbose_name='Наименование компетенции')),
                ('number', models.IntegerField(verbose_name='Номер компетенции')),
            ],
            options={
                'verbose_name': 'компетенция программы',
                'verbose_name_plural': 'компетенции программы',
            },
        ),
        migrations.CreateModel(
            name='ProgramModules',
            fields=[
                ('archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('status', models.CharField(choices=[('h', 'Скрыт'), ('p', 'Опубликован')], default='h', max_length=1, verbose_name='Статус публикации')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semester', models.PositiveIntegerField(blank=True, null=True)),
                ('choice_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.ChoiceGroup')),
                ('competence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.ProgramCompetence')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.Module')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Program')),
            ],
            options={
                'verbose_name': 'модуль программы',
                'verbose_name_plural': 'модули программы',
            },
        ),
        migrations.CreateModel(
            name='TargetModules',
            fields=[
                ('archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('status', models.CharField(choices=[('h', 'Скрыт'), ('p', 'Опубликован')], default='h', max_length=1, verbose_name='Статус публикации')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('choice_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.ChoiceGroup')),
                ('program_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.ProgramModules')),
            ],
            options={
                'verbose_name': 'модуль цели',
                'verbose_name_plural': 'модули цели',
            },
        ),
        migrations.CreateModel(
            name='TrainingTarget',
            fields=[
                ('archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('status', models.CharField(choices=[('h', 'Скрыт'), ('p', 'Опубликован')], default='h', max_length=1, verbose_name='Статус публикации')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=256, verbose_name='Наименование образовательной цели')),
                ('number', models.IntegerField(verbose_name='Порядковый номер цели')),
                ('program', models.ManyToManyField(to='programs.Program')),
            ],
            options={
                'verbose_name': 'образовательная цель',
                'verbose_name_plural': 'образовательные цели',
            },
        ),
        migrations.AddField(
            model_name='targetmodules',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.TrainingTarget'),
        ),
        migrations.AddField(
            model_name='choicegroup',
            name='choice_group_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.ChoiceGroupType'),
        ),
        migrations.AddField(
            model_name='choicegroup',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Program'),
        ),
    ]
