# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_remove_module_dependencies'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleDependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('soft', 'мягкая'), ('hard', 'строгая')], default='hard', max_length=4, verbose_name='Тип зависимости')),
                ('dependencies', models.ManyToManyField(related_name='modules', to='modules.Module')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module', to='modules.Module')),
            ],
            options={
                'verbose_name': 'зависимость',
                'verbose_name_plural': 'зависимости',
            },
        ),
        migrations.AddField(
            model_name='program',
            name='module_dependencies',
            field=models.ManyToManyField(to='programs.ModuleDependency', verbose_name='Зависимости модулей'),
        ),
    ]
