# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_auto_20161203_0138'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='choice_pool',
            new_name='choice_modules',
        ),
        migrations.AddField(
            model_name='program',
            name='chief',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.Person'),
        ),
        migrations.AddField(
            model_name='program',
            name='title',
            field=models.CharField(default='', max_length=256, verbose_name='Название образовательной программы'),
        ),
        migrations.AlterField(
            model_name='program',
            name='educational_program_trajectories',
            field=models.ManyToManyField(to='modules.EducationalProgramTrajectoriesPool', verbose_name='Траектория образовательной программы'),
        ),
        migrations.AlterField(
            model_name='program',
            name='general_base_modules',
            field=models.ManyToManyField(to='modules.GeneralBaseModulesPool', verbose_name='Общепрофессиональные базовые модули'),
        ),
    ]
