# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'программа', 'verbose_name_plural': 'программы'},
        ),
        migrations.AddField(
            model_name='program',
            name='choice_modules',
            field=models.ManyToManyField(to='modules.ChoiceModulesPool', verbose_name='Пул модулей по выбору'),
        ),
        migrations.AddField(
            model_name='program',
            name='educational_program_trajectories',
            field=models.ManyToManyField(to='modules.EducationalProgramTrajectoriesPool', verbose_name='Траектории образовательной программы'),
        ),
        migrations.AddField(
            model_name='program',
            name='general_base_modules',
            field=models.ManyToManyField(to='modules.GeneralBaseModulesPool', verbose_name='Общепрофессиональные базовые модули'),
        ),
        migrations.AlterField(
            model_name='program',
            name='chief',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.Person', verbose_name='Руководитель образовательной программы'),
        ),
    ]
