# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='level',
            field=models.CharField(choices=[('b', 'бакалавриат'), ('m', 'магистратура'), ('m', 'специалитет')], default='b', max_length=1, verbose_name='Уровень программы'),
        ),
    ]
