# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('competences', '0002_competence_profession'),
        ('modules', '0004_auto_20170220_1112'),
        ('programs', '0002_program_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceGroup',
            fields=[
                ('archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('status', models.CharField(choices=[('h', 'Скрыт'), ('p', 'Опубликован')], default='h', max_length=1, verbose_name='Статус публикации')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=2048, verbose_name='Наименование группы выбора')),
                ('labor', models.IntegerField(default=3, max_length=3, verbose_name='Трудоёмкость группы')),
                ('number', models.IntegerField(verbose_name='Номер группы выбора')),
            ],
            options={
                'verbose_name_plural': 'группы выбора',
                'verbose_name': 'группа выбора',
            },
        ),
        migrations.CreateModel(
            name='ChoiceGroupType',
            fields=[
                ('archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('status', models.CharField(choices=[('h', 'Скрыт'), ('p', 'Опубликован')], default='h', max_length=1, verbose_name='Статус публикации')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=2048, verbose_name='Наименование типы группы выбора')),
            ],
            options={
                'verbose_name_plural': 'типы группы выбора',
                'verbose_name': 'тип группы выбора',
            },
        ),
        migrations.CreateModel(
            name='ProgramCompetence',
            fields=[
                ('archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('status', models.CharField(choices=[('h', 'Скрыт'), ('p', 'Опубликован')], default='h', max_length=1, verbose_name='Статус публикации')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=2048, verbose_name='Наименование компетенции')),
                ('number', models.IntegerField(verbose_name='Номер компетенции')),
            ],
            options={
                'verbose_name_plural': 'компетенции программы',
                'verbose_name': 'компетенция программы',
            },
        ),
        migrations.CreateModel(
            name='ProgramModules',
            fields=[
                ('archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('status', models.CharField(choices=[('h', 'Скрыт'), ('p', 'Опубликован')], default='h', max_length=1, verbose_name='Статус публикации')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField(verbose_name='Начало периода освоения')),
                ('period_end', models.DateField(verbose_name='Конец периода освоения')),
                ('choice_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.ChoiceGroup')),
                ('competence', models.ManyToManyField(blank=True, to='competences.Competence')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.Module')),
            ],
            options={
                'verbose_name_plural': 'модули программы',
                'verbose_name': 'модуль программы',
            },
        ),
        migrations.CreateModel(
            name='TargetModules',
            fields=[
                ('archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('status', models.CharField(choices=[('h', 'Скрыт'), ('p', 'Опубликован')], default='h', max_length=1, verbose_name='Статус публикации')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('choice_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.ChoiceGroup')),
                ('program_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.ProgramModules')),
            ],
            options={
                'verbose_name_plural': 'модули цели',
                'verbose_name': 'модуль цели',
            },
        ),
        migrations.CreateModel(
            name='TrainingTarget',
            fields=[
                ('archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('status', models.CharField(choices=[('h', 'Скрыт'), ('p', 'Опубликован')], default='h', max_length=1, verbose_name='Статус публикации')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=256, verbose_name='Наименование образовательной цели')),
                ('number', models.IntegerField(verbose_name='Порядковый номер цели')),
            ],
            options={
                'verbose_name_plural': 'образовательные цели',
                'verbose_name': 'образовательная цель',
            },
        ),
        migrations.RemoveField(
            model_name='moduledependency',
            name='module',
        ),
        migrations.RemoveField(
            model_name='moduledependency',
            name='modules',
        ),
        migrations.RemoveField(
            model_name='program',
            name='choice_modules',
        ),
        migrations.RemoveField(
            model_name='program',
            name='educational_program_trajectories',
        ),
        migrations.RemoveField(
            model_name='program',
            name='module_dependencies',
        ),
        migrations.RemoveField(
            model_name='program',
            name='modules',
        ),
        migrations.AddField(
            model_name='program',
            name='competences',
            field=models.ManyToManyField(blank=True, to='competences.Competence'),
        ),
        migrations.AddField(
            model_name='program',
            name='training_direction',
            field=models.CharField(default='', max_length=256, verbose_name='Направление подготовки'),
        ),
        migrations.AlterField(
            model_name='program',
            name='level',
            field=models.CharField(choices=[('b', 'бакалавриат'), ('m', 'магистратура'), ('s', 'специалитет')], default='b', max_length=1, verbose_name='Уровень программы'),
        ),
        migrations.AlterField(
            model_name='program',
            name='title',
            field=models.CharField(default='', max_length=256, verbose_name='Наименование образовательной программы'),
        ),
        migrations.DeleteModel(
            name='ModuleDependency',
        ),
        migrations.AddField(
            model_name='trainingtarget',
            name='program',
            field=models.ManyToManyField(to='programs.Program'),
        ),
        migrations.AddField(
            model_name='targetmodules',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.TrainingTarget'),
        ),
        migrations.AddField(
            model_name='programmodules',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Program'),
        ),
        migrations.AddField(
            model_name='choicegroup',
            name='choice_group_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.ChoiceGroupType'),
        ),
        migrations.AddField(
            model_name='choicegroup',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Program'),
        ),
    ]
