# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_auto_20161203_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='chief',
        ),
    ]
