# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_auto_20161213_0102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moduledependency',
            old_name='dependencies',
            new_name='modules',
        ),
        migrations.RemoveField(
            model_name='program',
            name='module_dependencies',
        ),
        migrations.AddField(
            model_name='moduledependency',
            name='program',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.Program'),
        ),
    ]
