# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_auto_20161203_0138'),
        ('programs', '0003_remove_program_chief'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='chief',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.Person'),
        ),
    ]
