# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_auto_20161213_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduledependency',
            name='modules',
            field=models.ManyToManyField(null=True, related_name='modules', to='modules.Module'),
        ),
    ]
