# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_auto_20170220_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicegroup',
            name='labor',
            field=models.IntegerField(default=3, verbose_name='Трудоёмкость группы'),
        ),
        migrations.AlterField(
            model_name='program',
            name='chief',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.Person', verbose_name='Руководитель образовательной программы'),
        ),
    ]
