# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_auto_20170220_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmodules',
            name='competence',
            field=models.ManyToManyField(blank=True, to='programs.ProgramCompetence'),
        ),
    ]
