# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_auto_20161213_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduledependency',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='modules', to='modules.Module'),
        ),
        migrations.AlterField(
            model_name='moduledependency',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.Program'),
        ),
    ]
