# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_program_chief'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='choice_modules',
        ),
        migrations.RemoveField(
            model_name='program',
            name='educational_program_trajectories',
        ),
        migrations.RemoveField(
            model_name='program',
            name='general_base_modules',
        ),
    ]
