# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_auto_20170222_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmodules',
            name='competence',
        ),
        migrations.AddField(
            model_name='programmodules',
            name='competence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.ProgramCompetence'),
        ),
    ]
