# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_auto_20161213_0312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduledependency',
            name='program',
        ),
        migrations.AddField(
            model_name='program',
            name='module_dependencies',
            field=models.ManyToManyField(to='programs.ModuleDependency', verbose_name='Зависимости модулей'),
        ),
    ]
