# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-12 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_auto_20170227_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmodules',
            name='period_end',
        ),
        migrations.RemoveField(
            model_name='programmodules',
            name='period_start',
        ),
        migrations.AddField(
            model_name='programmodules',
            name='semester',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
