# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_merge_20161216_1506'),
        ('programs', '0006_auto_20161215_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='general_base_modules',
        ),
        migrations.AddField(
            model_name='program',
            name='modules',
            field=models.ManyToManyField(blank=True, to='modules.Module', verbose_name='Модули программы'),
        ),
        migrations.AlterField(
            model_name='program',
            name='chief',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.Person', verbose_name='Руководитель образовательной программы'),
        ),
        migrations.AlterField(
            model_name='program',
            name='choice_modules',
            field=models.ManyToManyField(blank=True, to='modules.ChoiceModulesPool', verbose_name='Пул модулей по выбору'),
        ),
        migrations.AlterField(
            model_name='program',
            name='educational_program_trajectories',
            field=models.ManyToManyField(blank=True, to='modules.EducationalProgramTrajectoriesPool', verbose_name='Траектории образовательной программы'),
        ),
        migrations.AlterField(
            model_name='program',
            name='module_dependencies',
            field=models.ManyToManyField(blank=True, to='programs.ModuleDependency', verbose_name='Зависимости модулей'),
        ),
    ]
