# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('status', models.CharField(choices=[('h', 'Скрыт'), ('p', 'Опубликован')], default='h', max_length=1, verbose_name='Статус публикации')),
                ('title', models.CharField(default='', max_length=256, verbose_name='Название дисциплины')),
                ('description', models.TextField(blank=True, max_length=16384, null=True, verbose_name='Короткое описание')),
                ('labor', models.PositiveIntegerField(default=0, verbose_name='зачётных единиц')),
                ('period', models.IntegerField(default=1, verbose_name='Период освоения в модуле')),
                ('form', models.CharField(choices=[('e', 'Экзамен'), ('z', 'Зачет')], default='z', max_length=1, verbose_name='Форма контроля')),
                ('results_text', models.TextField(blank=True, default='', max_length=16384, verbose_name='Результаты обучения')),
                ('uni_uid', models.CharField(blank=True, max_length=256, null=True)),
                ('uni_discipline', models.CharField(blank=True, max_length=256, null=True)),
                ('uni_number', models.CharField(blank=True, max_length=256, null=True)),
                ('uni_section', models.CharField(blank=True, max_length=256, null=True)),
                ('uni_file', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'дисциплина',
                'verbose_name_plural': 'дисциплины',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField(default=1970, verbose_name='Год поступления')),
                ('admission_semester', models.PositiveIntegerField(default=0, verbose_name='Семестр поступления')),
                ('training_semester', models.PositiveIntegerField(default=0, verbose_name='Семестр изучения')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplines.Discipline')),
            ],
            options={
                'verbose_name': 'семестр изучения дисциплины',
                'verbose_name_plural': 'семестры изучения дисциплины',
            },
        ),
        migrations.CreateModel(
            name='TrainingTerms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=256, verbose_name='Наименование срока обучения')),
                ('limit', models.PositiveIntegerField(default=0, verbose_name='Лимит ЗЕ в год')),
            ],
            options={
                'verbose_name': 'срок обучения',
                'verbose_name_plural': 'сроки обучения',
            },
        ),
    ]
