# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('results', '0001_initial'),
        ('disciplines', '0001_initial'),
        ('programs', '0001_initial'),
        ('courses', '0001_initial'),
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Program'),
        ),
        migrations.AddField(
            model_name='semester',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disciplines.TrainingTerms'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='courses',
            field=models.ManyToManyField(blank=True, to='courses.Course', verbose_name='Варианты реализации дисциплины'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.Module'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='results',
            field=models.ManyToManyField(blank=True, to='results.Result', verbose_name='Результаты обучения'),
        ),
    ]
