# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0002_discipline_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='form',
            field=models.CharField(choices=[('e', 'Экзамен'), ('z', 'Зачет')], default='z', max_length=1, verbose_name='Форма контроля'),
        ),
    ]
