# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0003_discipline_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='description',
            field=models.TextField(blank=True, max_length=16384, null=True, verbose_name='Короткое описание'),
        ),
    ]
