# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_remove_module_disciplines'),
        ('disciplines', '0004_discipline_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.Module'),
        ),
    ]
