# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0006_auto_20161221_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discipline',
            old_name='points',
            new_name='labor',
        ),
    ]
