# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0007_auto_20170222_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='period',
            field=models.IntegerField(default=1, max_length=2, verbose_name='Период освоения в модуле'),
        ),
    ]
