# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-12 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0008_discipline_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discipline',
            old_name='name',
            new_name='title',
        ),
    ]
